### ISSUE TITLE
头部标签Tag的抖动问题

### ISSUE THREAD

**Issue by tangent1231** [xcpcio/xcpcio#13]
因为时间变化，数字长度会影响整体的宽度，导致会出现标签这一行会左右的抖动。
![image](https://github.com/XCPCIO/board/assets/41216851/faf4efb1-f74f-4dda-af30-9e2a5b45a913)

**Comment by Dup4** [comment]
Board-NG 里改成了等宽字体，会 fix 由于时间变化导致的抖动问题
