### ISSUE TITLE
墙外网络访问不了

### ISSUE THREAD

**Issue by joyemang33** [xcpcio/xcpcio#141]
在新加坡访问board.xcpcio.com会直接限制一个"_Failed to fetch_"界面

**Comment by Dup4** [comment]
<img width="518" alt="image" src="https://github.com/xcpcio/xcpcio/assets/38343778/7330d600-29de-4651-b397-739efaf5b589">

可以把鼠标悬停在 `Contact` 上截图给我看看吗

**Comment by joyemang33** [comment]
![image](https://github.com/xcpcio/xcpcio/assets/37923722/87e99452-3d63-4810-b564-7e8460b262cc)

谢谢！

**Comment by Dup4** [comment]
现在应该可以了对吧？我做了点调整

**Comment by joyemang33** [comment]
> 现在应该可以了对吧？我做了点调整

可以了，多谢！
