### ISSUE TITLE
cdn.xcpcio.com 被解析到 127.0.0.1，board.xcpcio.com 因此不可用

### ISSUE THREAD

**Issue by Zxilly** [xcpcio/xcpcio#249]
https://www.boce.com/dns/20240908_ee06da51e1292f1568bda341b7b24fab.html

![image](https://github.com/user-attachments/assets/8a7dc993-782c-4829-8a04-1929ad7bc7f8)

**Comment by Dup4** [comment]
当前时间段的 board.xcpcio.com 并不依赖 cdn.xcpcio.com

**Comment by Zxilly** [comment]
![image](https://github.com/user-attachments/assets/9dde7933-2e5f-4914-a538-315aefea6cb9)

似乎是因为先前注册的 service-worker 导致了此错误，应该强制过期之前的 service-worker
