### ISSUE TITLE
搞错榜单

### ISSUE THREAD

**Issue by k1nsom** [xcpcio/xcpcio#251]
![image](https://github.com/user-attachments/assets/73f7b1c5-c7e3-4578-adb3-98653abe98d4)
![image](https://github.com/user-attachments/assets/1d3184e9-8c40-47f1-94f2-2659480af6ec)
这个队伍第一场网络赛的罚时搞错了

**Comment by Dup4** [comment]
<img width="1799" alt="image" src="https://github.com/user-attachments/assets/8a6f1bd8-9ca0-4ec1-ac9f-1eb48fc8972a">

已修复
