### ISSUE TITLE
board页面增加retun按钮跳转至boardList

### ISSUE THREAD

**Issue by Kwords** [xcpcio/xcpcio#4]
手机用户比较需要，例如qq链接查看某个榜单，想看另一场比赛需要关闭页面重新找另一个榜单的url

**Comment by Dup4** [comment]
<img width="1715" alt="image" src="https://github.com/xcpcio/xcpcio/assets/38343778/97dab26b-02be-4121-a305-ef779b93a896">

Board-NG 里加上了
